### ISSUE TITLE
Proxyチェックのメッセージが「どのプレイヤーによるものか」がいまいちわかりにくい、なんならEmbedでもいいかも

### ISSUE THREAD

**Issue by jaotan** [jaoafa/MyMaid3#2]
## Contents
```
Proxyチェックのメッセージが「どのプレイヤーによるものか」がいまいちわかりにくい、なんならEmbedでもいいかも
```
## Message URL
https://discord.com/channels/597378876556967936/626727474922913792/815354742456713296

**Comment by book000** [comment]
https://github.com/jaoafa/AntiAlts3/commit/907e7f8ad9d65383e03700f4259e86b09a1c7ff7 にて追加
